<?php

namespace app\modules\translates\models;

use Yii;

/**
 * This is the model class for table "langs".
 *
 * @property int $id
 * @property string $name Наименование
 * @property string $url Код языка
 * @property string $image Картинка
 * @property int $status Статус
 * @property bool $default Язык по умолчанию
 *
 * @property Message[] $messages
 */
class Langs extends \yii\db\ActiveRecord
{
    /**
     * rasm yuklash uchun kerak
     * @var
     */
    public $flag;
    const MAIN_LANGUAGE = 'uz';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%langs}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status'], 'default', 'value' => 0],
            [['status'], 'integer'],
            [['default'], 'boolean'],
            [['flag'],'safe'],
            [['name', 'url', 'image'], 'string', 'max' => 255],
            [['name' ,'url'],'required']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => Yii::t('app','Name'),
            'url' => Yii::t('app','Key'),
            'status' => Yii::t('app','Status'),
            'default' => Yii::t('app','Default'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages()
    {
        return $this->hasMany(Message::className(), ['lang_id' => 'id']);
    }


    /**
     * default til
     */
    public function defaultLang()
    {
        if($this->default == 1){
            $all_lang = Langs::find()->where(['!=', 'id', $this->id])->all();
            foreach ($all_lang as $value){
                $value->default = 0;
                $value->save();
            }
        }
    }


    /**
     * udalit qilgandan keyin rasmlarni ochirish
     * @return bool
     */
    public function beforeDelete()
    {
        $dir = '/web/uploads/flags/';
        if($this->image != null){
                unlink($dir . $this->image);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


    /**
     * tillar listi
     * @return mixed
     */
    public static function getLanguages()
    {
        return Langs::find()->where(['status'=>1])->orderBy(['default' => SORT_DESC])->all();
    }

    /**
     * Получение текущего объекта языка
     * @return mixed
     */
    static function getCurrent()
    {
        return Langs::find()->where(['url'=>Yii::$app->language])->one();
    }


    /**
     * status listini olish
     * @return string[]
     */
    public function getStatus()
    {
        return [
            '0' => Yii::t('app','Inactive'),
            '1' => Yii::t('app','Active'),
        ];
    }


    /**
     * status teksti
     * @return string
     */
    public function getStatusType(){
        switch ($this->status) {
            case 0: return Yii::t('app','Inactive');
            case 1: return Yii::t('app','Active');
        }
    }


    /**
     * status
     * @return string
     */
    public function StatusName()
    {
        return ($this->status=='1')?Yii::t('app','Active'):Yii::t('app','Inactive');
    }


    /**
     * bayroqni olish
     * @return string
     */
    public function getFlag()
    {
        if ($this->image == '') {
            $path = '/uploads/flags/noflag.png';
        } else {
            $path = Yii::$app->params['siteName'].'/web/uploads/flags/'.$this->image;
        }
        return $path;
    }


    /**
     * file upload qilish
     * @throws \yii\db\Exception
     */
    public function upload()
    {
        $fileName = $this->id.$this->url.'.'.$this->flag->extension;
        if(!empty($this->flag))
        {
            if(file_exists('uploads/flags/'.$this->image) && $this->image != null)
            {
                unlink('uploads/flags/'.$this->image);
            }

            $this->flag->saveAs('uploads/flags/'.$fileName);
            Yii::$app->db->createCommand()->update('langs', ['image' => $fileName], [ 'id' => $this->id ])->execute();
        }
    }
}
