<?php

namespace app\modules\regions\models;

use Yii;
use app\modules\translates\models\Langs;
use app\modules\translates\models\Translates;
use app\modules\countries\models\Countries;
/**
 * This is the model class for table "{{%regions}}".
 *
 * @property int $id
 * @property string|null $name Наименование
 *
 * @property Districts[] $districts
 * @property Users[] $users
 */
class Regions extends \yii\db\ActiveRecord
{
    public $tr_name;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%regions}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['key'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['country_id'], 'exist', 'skipOnError' => true, 'targetClass' => Countries::className(), 'targetAttribute' => ['country_id' => 'id']],
            [['tr_name'],'safe'],
            [['tr_name'],'validateName']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'country_id' => 'Countrie ID',
            'key' => Yii::t('app', 'Key'),
            'tr_name' => Yii::t('app', 'Name'),
        ];
    }

    public function getDistrictDataProvider()
    {
        $searchModel = new DistrictsSearch(['region_id' => $this->id]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $dataProvider;
    }
     /**
     * Gets query for [[Districts]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDistricts()
    {
        return $this->hasMany(Districts::className(), ['region_id' => 'id']);
    }

    /**
     * Gets query for [[Countrie]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCountrie()
    {
        return $this->hasOne(Countries::className(), ['id' => 'country_id']);
    }

    /**
     * Gets query for [[Users]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(Users::className(), ['place_of_birth_region_id' => 'id']);
    }

    /**
     * Gets query for [[Users0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsers0()
    {
        return $this->hasMany(Users::className(), ['place_of_residence_region_id' => 'id']);
    }

    public static function TranslatableFields()
    {
        return [
          'name' => 'tr_name'
        ];
    }

    public function validateName($attr)
    {
        $available_languages = Langs::getLanguages();
        $valid = $this->$attr[Langs::MAIN_LANGUAGE];
        foreach ($available_languages as $available_language){
            $valid = $valid && $this->$attr[$available_language->url];
            if(!$valid){
                $this->addError($attr,Yii::t('app','You should add all translations {attribute} !'));
            }
        }
    }

    public function getTranslate()
    {
        return $this->hasOne(Translates::className(), ['field_id' => 'id'])
            ->where(['table_name'=>self::tableName(),'field_name'=>'name' , 'language_code' =>Yii::$app->language ]);
    }

    public function beforeSave($insert)
    {
        $translatable_fields = self::TranslatableFields();
        //saqlashdan oldin asosiy tilda kiritilgan malumotlar ni asosiy jadvalga yozish
        foreach ($translatable_fields as $key => $translatable_field) {
            $this->$key = $this->$translatable_field[Langs::MAIN_LANGUAGE];
        }
        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        // tarjimalarni saqlash
        $this->setTranslates();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    // asosiy tildan boshqa tilda kiritilgan tarjimalarni saqlash uchun
    public function setTranslates()
    {
        $available_languages = Langs::getLanguages();
        $translatable_fields = self::TranslatableFields();
        $data = [];

        // barcha tarjimalrni massivga yiigb olish
        foreach ($available_languages as $available_language) {
            foreach ($translatable_fields as $key => $translatable_field){
                // asosiy til uchun kiritilgan tarjimalar asosiy jadvalga yoziladi
                if($available_language->url != Langs::MAIN_LANGUAGE && $this->$translatable_field[$available_language->url]){
                    $data[] = [
                        $this->tableName(),
                        $this->id,
                        $key,
                        $this->$translatable_field[$available_language->url],
                        $available_language->url
                    ];
                }
            }
        }
        if(!empty($data)){
            //barcha tarjimalarni tarjimalar jadvaliga saqlash
            Yii::$app->db
                ->createCommand()
                ->batchInsert('{{%translates}}', [
                        'table_name',
                        'field_id',
                        'field_name',
                        'field_value',
                        'language_code'
                    ],$data)
                ->execute();
        }

    }

    public function getTranslates()
    {
        $translatable_fields = self::TranslatableFields();

        // aynan shu model ga tegishli barcha tarjimalarni olish
        $translates = (new \yii\db\Query())
            ->select('field_name,group_concat(field_value) as values,group_concat(language_code) as keys')
            ->from("{{%translates}}")
            ->where([ 'field_id' => $this->id])
            ->groupBy('field_name')
            ->all();

        // tarjimalar jadvalidan tarjimalarni yordamchi massivga yuklab olamiz
        foreach ($translates as $translate) {
            $arr = array_combine(explode(',',$translate['keys']), explode(',',$translate['values']));
            $this->{$translatable_fields[$translate['field_name']]} = $arr;
        }

        // asosiy jadvaldagi tarjimalarni yordamchi massivga yuklab olish
        foreach ($translatable_fields as $key => $translatable_field) {
            $this->{$translatable_field}[Langs::MAIN_LANGUAGE] = $this->{$key};
        }

    }
}
