<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;
use app\modules\translates\models\Langs;
use app\modules\translates\models\Translates;
/**
 * This is the model class for table "_table_of_blog_categories".
 *
 * @property int $id
 * @property string|null $slug slug
 * @property int|null $status status
 * @property int|null $created_at created_at
 * @property int|null $updated_at updated_at
 *
 * @property BlogCategoriesRelations[] $blogCategoriesRelations
 */
class BlogCategories extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $tr_name;
    public static function tableName()
    {
        return '{{%blog_categories}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status',], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['slug'], 'string', 'max' => 255],
            [['tr_name'],'safe'],
            [['tr_name'],'validateName']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'tr_name' => 'Название',
            'slug' => 'Слуг',
            'status' => 'Статус',
            'created_at' => 'Созданный',
            'updated_at' => 'Обновлено',
        ];
    }
    /**
     * Gets query for [[BlogCategoriesRelations]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getBlogCategoriesRelations()
    {
        return $this->hasMany(BlogCategoriesRelations::className(), ['blog_category_id' => 'id']);
    }
    public function getStatus()
    {
        return ArrayHelper::map([
            ['id' => '1', 'status' => 'Актив',],
            ['id' => '2', 'status' => 'Не Актив',],
        ],
        'id', 'status');
    }
    public static function TranslatableFields()
    {
        return [
            'name' => 'tr_name',
        ];
    }

    public function validateName($attr)
    {
        $available_languages = Langs::getLanguages();
        $valid = $this->$attr[Langs::MAIN_LANGUAGE];
        foreach ($available_languages as $available_language){
            $valid = $valid && $this->$attr[$available_language->url];
            if(!$valid){
                $this->addError($attr,Yii::t('app','You should add all translations {attribute} !'));
            }
        }
    }

    public function getTranslate()
    {
        return $this->hasOne(Translates::className(), ['field_id' => 'id'])
            ->where(['table_name'=>self::tableName(),'field_name'=>'name' , 'language_code' =>Yii::$app->language ]);
    }
    public function beforeSave($insert)
    {
        $translatable_fields = self::TranslatableFields();
        //saqlashdan oldin asosiy tilda kiritilgan malumotlar ni asosiy jadvalga yozish
        foreach ($translatable_fields as $key => $translatable_field) {
            $this->$key = $this->$translatable_field[Langs::MAIN_LANGUAGE];
        }
        if($this->updated_at != null ) $this->updated_at = \Yii::$app->formatter->asDate($this->updated_at, 'php:Y-m-d');
        if ($this->isNewRecord)
        {
            if($this->created_at != null ) $this->created_at = \Yii::$app->formatter->asDate($this->created_at, 'php:Y-m-d');
        }
        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        // tarjimalarni saqlash
        $this->setTranslates();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    // asosiy tildan boshqa tilda kiritilgan tarjimalarni saqlash uchun
    public function setTranslates()
    {
        $available_languages = Langs::getLanguages();
        $translatable_fields = self::TranslatableFields();
        $data = [];

        // barcha tarjimalrni massivga yiigb olish
        foreach ($available_languages as $available_language) {
            foreach ($translatable_fields as $key => $translatable_field){
                // asosiy til uchun kiritilgan tarjimalar asosiy jadvalga yoziladi
                if($available_language->url != Langs::MAIN_LANGUAGE && $this->$translatable_field[$available_language->url]){
                    $data[] = [
                        $this->tableName(),
                        $this->id,
                        $key,
                        $this->$translatable_field[$available_language->url],
                        $available_language->url
                    ];
                }
            }
        }
        if(!empty($data)){
            //barcha tarjimalarni tarjimalar jadvaliga saqlash
            Yii::$app->db
                ->createCommand()
                ->batchInsert('{{%translates}}', [
                    'table_name',
                    'field_id',
                    'field_name',
                    'field_value',
                    'language_code'
                ],$data)
                ->execute();
        }

    }
    public function getTranslates()
    {
        $translatable_fields = self::TranslatableFields();

        // aynan shu model ga tegishli barcha tarjimalarni olish
        $translates = (new \yii\db\Query())
            ->select('field_name,group_concat(field_value) as values,group_concat(language_code) as keys')
            ->from("{{%translates}}")
            ->where([ 'field_id' => $this->id])
            ->groupBy('field_name')
            ->all();

        // tarjimalar jadvalidan tarjimalarni yordamchi massivga yuklab olamiz
        foreach ($translates as $translate) {
            $arr = array_combine(explode(',',$translate['keys']), explode(',',$translate['values']));
            $this->{$translatable_fields[$translate['field_name']]} = $arr;
        }

        // asosiy jadvaldagi tarjimalarni yordamchi massivga yuklab olish
        foreach ($translatable_fields as $key => $translatable_field) {
            $this->{$translatable_field}[Langs::MAIN_LANGUAGE] = $this->{$key};
        }

    }
}
