<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;
use app\modules\translates\models\Langs;
use app\modules\translates\models\Translates;   

/**
 * This is the model class for table "_table_of_sliders".
 *
 * @property int $id
 * @property string|null $url url
 * @property string|null $image image
 * @property int|null $status status
 * @property string|null $title title
 * @property string|null $description description
 *
 * @property SliderItems[] $sliderItems
 */
class Sliders extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $filePhoto;
    public $tr_title;
    public $tr_description;
    public static function tableName()
    {
        return '{{%sliders}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status'], 'integer'],
            [['description'], 'string'],
            [['url', 'image', 'title'], 'string', 'max' => 255],
            [['filePhoto'], 'file'],
            [['url'], 'required'],
            [['tr_title', 'tr_description'],'safe'],
            [['tr_title', 'tr_description'],'validateName']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'url' => 'Url',
            'image' => 'Изображение',
            'filePhoto' => 'Изображение',
            'status' => 'Статус',
            'title' => 'Заголовок',
            'description' => 'Описание',
            'tr_title' => 'Заголовок',
            'tr_description' => 'Описание',
        ];
    }

    /**
     * Gets query for [[SliderItems]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSliderItems()
    {
        return $this->hasMany(SliderItems::className(), ['sider_id' => 'id']);
    }

    public static function TranslatableFields()
    {
        return [
            'title' => 'tr_title',
            'description' => 'tr_description'
        ];
    }

    public function validateName($attr)
    {
        $available_languages = Langs::getLanguages();
        $valid = $this->$attr[Langs::MAIN_LANGUAGE];
        foreach ($available_languages as $available_language){
            $valid = $valid && $this->$attr[$available_language->url];
            if(!$valid){
                $this->addError($attr,Yii::t('app','You should add all translations {attribute} !'));
            }
        }
    }

    public function getTranslate()
    {
        return $this->hasOne(Translates::className(), ['field_id' => 'id'])
            ->where(['table_name'=>self::tableName(),'field_name'=>'title' , 'language_code' =>Yii::$app->language ]);
    }
    public function beforeSave($insert)
    {
        $translatable_fields = self::TranslatableFields();
        //saqlashdan oldin asosiy tilda kiritilgan malumotlar ni asosiy jadvalga yozish
        foreach ($translatable_fields as $key => $translatable_field) {
            $this->$key = $this->$translatable_field[Langs::MAIN_LANGUAGE];
        }
        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        // tarjimalarni saqlash
        $this->setTranslates();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    // asosiy tildan boshqa tilda kiritilgan tarjimalarni saqlash uchun
    public function setTranslates()
    {
        $available_languages = Langs::getLanguages();
        $translatable_fields = self::TranslatableFields();
        $data = [];

        // barcha tarjimalrni massivga yiigb olish
        foreach ($available_languages as $available_language) {
            foreach ($translatable_fields as $key => $translatable_field){
                // asosiy til uchun kiritilgan tarjimalar asosiy jadvalga yoziladi
                // if($available_language->url != Langs::MAIN_LANGUAGE && $this->$translatable_field[$available_language->url]){
                if($this->$translatable_field[$available_language->url]){
                    $data[] = [
                        $this->tableName(),
                        $this->id,
                        $key,
                        $this->$translatable_field[$available_language->url],
                        $available_language->url
                    ];
                }
            }
        }
        if(!empty($data)){
            //barcha tarjimalarni tarjimalar jadvaliga saqlash
            Yii::$app->db
                ->createCommand()
                ->batchInsert('{{%translates}}', [
                    'table_name',
                    'field_id',
                    'field_name',
                    'field_value',
                    'language_code'
                ],$data)
                ->execute();
        }

    }
    public function getTranslates()
    {
        $translatable_fields = self::TranslatableFields();

        // aynan shu model ga tegishli barcha tarjimalarni olish
        $translates = (new \yii\db\Query())
            ->select('field_name,group_concat(field_value) as values,group_concat(language_code) as keys')
            ->from("{{%translates}}")
            ->where([ 'field_id' => $this->id])
            ->groupBy('field_name')
            ->all();

        // tarjimalar jadvalidan tarjimalarni yordamchi massivga yuklab olamiz
        foreach ($translates as $translate) {
            $arr = array_combine(explode(',',$translate['keys']), explode(',',$translate['values']));
            $this->{$translatable_fields[$translate['field_name']]} = $arr;
        }

        // asosiy jadvaldagi tarjimalarni yordamchi massivga yuklab olish
        foreach ($translatable_fields as $key => $translatable_field) {
            $this->{$translatable_field}[Langs::MAIN_LANGUAGE] = $this->{$key};
        }

    }
}
