<?php

namespace app\models;
use app\modules\countries\models\Countries;
use app\modules\regions\models\Regions;
use app\modules\regions\models\Districts;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "_table_of_users".
 *
 * @property int $id
 * @property string|null $username Логин
 * @property int|null $status Статус пользователя* 1 => Aktiv, 2 => No Aktiv, 3 => Blocked, 4 => Del
 * @property string|null $password Пароль
 * @property string|null $avatar Аватар
 * @property string|null $fio ФИО
 * @property string|null $phone Телефон номер
 * @property string|null $last_seen Последное активность
 * @property string|null $birthday Дата рождение
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $new_password;
    public $file;
    public static function tableName()
    {
        return '{{%users}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'country_id', 'district_id' , 'region_id'], 'integer'],
            [['last_seen', 'birthday', 'created_at', 'updated_at'], 'safe'],
            [['file',], 'file'],
            ['username', 'unique'],
            [['selected_langauge', 'auth_key','username', 'password', 'password_reset_token', 'email', 'email_verification_key', 'new_password','avatar', 'fio', 'phone'], 'string', 'max' => 255],
            [['fio',  'username', 'password', 'status'], 'required'],
            ['email', 'email'],
        ];
    }

    public function beforeSave($insert)
    {
        if($this->birthday != null ) $this->birthday = \Yii::$app->formatter->asDate($this->birthday, 'php:Y-m-d');
        if($this->updated_at != null ) $this->updated_at = \Yii::$app->formatter->asDate($this->updated_at, 'php:Y-m-d');
        if ($this->isNewRecord)
        {
            $this->password = Yii::$app->security->generatePasswordHash($this->password);
            if($this->created_at != null ) $this->created_at = \Yii::$app->formatter->asDate($this->created_at, 'php:Y-m-d');
        }
        if($this->new_password != null) $this->password = Yii::$app->security->generatePasswordHash($this->new_password);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Имя пользователя',
            'status' => 'Статус',
            'password' => 'Пароль',
            'new_password' => 'Новый пароль',
            'country_id' => 'Страна',
            'region_id' => 'Область',
            'district_id' => 'Район',
            'avatar' => 'Картина',
            'fio' => 'ФИО',
            'phone' => 'Телефон',
            'last_seen' => 'Время последней записи',
            'birthday' => 'Дата рождения',
            'email' => 'Электронное письмо',
            'created_at' => 'Созданный',
            'updated_at' => 'Обновлено',
        ];
    }
    public function getImage()
    {
        if($this->avatar != null && file_exists('uploads/avatar/'.$this->avatar)){
            return '/uploads/avatar/' . $this->avatar;
        }else{
            return '/uploads/avatar/noimg.png';
        }
    }
    public function getStatus()
    {
        return ArrayHelper::map([
            ['id' => '1', 'status' => 'Актив',],
            ['id' => '2', 'status' => 'Не Актив',],
            ['id' => '3', 'status' => 'Заблокировано',],
            ['id' => '4', 'status' => 'Удалено',],
        ],
        'id', 'status');
    }

    public function getCountry()
    {
        return $this->hasOne(Countries::className(), ['id' => 'country_id']);
    }

    /**
     * Gets query for [[District]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(Districts::className(), ['id' => 'district_id']);
    }

    /**
     * Gets query for [[Region]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRegion()
    {
        return $this->hasOne(Regions::className(), ['id' => 'region_id']);
    }
    public function getDistricts($id)
    {
        return ArrayHelper::map(Districts::find()->where(['region_id' => $id])->all(), 'id', 'name');
    }
    public function getRegions($id)
    {
        return ArrayHelper::map(Regions::find()->where(['country_id' => $id])->all(), 'id', 'name');
    }
    public function getCountries()
    {
        return ArrayHelper::map(Countries::find()->all(), 'id', 'name');
    }   
}
