<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "_table_of_user_blogs".
 *
 * @property int $id
 * @property string|null $author_username author_username
 * @property string|null $author_password_hash author_password_hash
 * @property int|null $user_id user_id
 *
 * @property Users $user
 */
class UserBlogs extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $new_password;
    public static function tableName()
    {
        return '{{%user_blogs}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id'], 'integer'],
            ['author_username', 'unique'],
            [['author_username', 'new_password', 'author_password_hash'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['author_username', 'author_password_hash',  'user_id'], 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'author_username' => 'Имя пользователя',
            'author_password_hash' => 'Пароль',
            'new_password' => 'Новый пароль',
            'user_id' => 'Пользователь',
        ];
    }
    public function beforeSave($insert)
    {
        if($this->new_password != null) $this->author_password_hash = Yii::$app->security->generatePasswordHash($this->new_password);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'user_id']);
    }
    public function getUsers()
    {
        $userRoles = UserRoles::find()->Where(['role_id' => 5])->all();
        $userArray = [];
        foreach ($userRoles as $userRole){
            $userArray  [] = $userRole->user_id;
        }
        return ArrayHelper::map(Users::find()->where(['id'=>$userArray])->all(), 'id', 'fio');
    }
}
